name: Merge conflicts
on:
  push:
    branches:
      - main
      - dev
jobs:
  triage:
    if: github.repository == 'mryan2005/hexo-theme-volantis'
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
